// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SWD.SportShirtShop.Repo.Entities;

public partial class Image
{
    public int Id { get; set; }

    public string Link { get; set; }

    public int? IdShirt { get; set; }
    [JsonIgnore]
    public virtual Shirt IdShirtNavigation { get; set; }
}