// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWD.SportShirtShop.Repo.Entities;

public partial class OrderDetail
{
    public int Id { get; set; }

    public int? IdOrders { get; set; }

    public int? IdShirt { get; set; }

    public int? Quantity { get; set; }

    public decimal? Price { get; set; }

    public decimal? Subtotal { get; set; }

    public virtual Order IdOrdersNavigation { get; set; }

    public virtual Shirt IdShirtNavigation { get; set; }
}