// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWD.SportShirtShop.Repo.Entities;

public partial class Payment
{
    public int Id { get; set; }

    public int? IdOrders { get; set; }

    public string Method { get; set; }

    public string Status { get; set; }

    public decimal? Price { get; set; }

    public string Note { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual Order IdOrdersNavigation { get; set; }
}