// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SWD.SportShirtShop.Repo.Entities;

public partial class PlayerInTournamentClub
{
    public int Id { get; set; }

    public int? IdTournamentClub { get; set; }

    public int? IdPlayer { get; set; }

    public int? Number { get; set; }

    public string PlayerName { get; set; }

    public string SeasonName { get; set; }

    public string ClubName { get; set; }

    public string Description { get; set; }
    [JsonIgnore]
    public virtual Player IdPlayerNavigation { get; set; }
    [JsonIgnore]
    public virtual TournamentClub IdTournamentClubNavigation { get; set; }
    [JsonIgnore]
    public virtual ICollection<Shirt> Shirts { get; set; } = new List<Shirt>();
}