// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SWD.SportShirtShop.Repo.Entities;

public partial class Player
{
    public int Id { get; set; }

    public int? IdClub { get; set; }

    public string Name { get; set; }

    public DateOnly? Dob { get; set; }

    public string Note { get; set; }

    public string Code { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? CreateAccount { get; set; }
    [JsonIgnore]
    public virtual Club IdClubNavigation { get; set; }
    [JsonIgnore]
    public virtual ICollection<PlayerInTournamentClub> PlayerInTournamentClubs { get; set; } = new List<PlayerInTournamentClub>();
}