// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SWD.SportShirtShop.Repo.Entities;

public partial class Shirt
{
    public int Id { get; set; }

    public int? IdShirtEdition { get; set; }

    public int? IdPlayerinTournamentClub { get; set; }

    public string Name { get; set; }

    public decimal? Price { get; set; }

    public decimal? SalePrice { get; set; }

    public int? TotalSold { get; set; }

    public string Description { get; set; }

    public int? QuantityStock { get; set; }

    public string Status { get; set; }

    public string Code { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? CreateAccount { get; set; }

    public DateTime? UpdatedDate { get; set; }
    [JsonIgnore]
    public virtual PlayerInTournamentClub IdPlayerinTournamentClubNavigation { get; set; }
    [JsonIgnore]
    public virtual ShirtEdition IdShirtEditionNavigation { get; set; }

    public virtual ICollection<Image> Images { get; set; } = new List<Image>();
    [JsonIgnore]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}