// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SWD.SportShirtShop.Repo.Entities;

public partial class TournamentClub
{
    public int Id { get; set; }

    public int? IdTournament { get; set; }

    public int? IdClub { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? CreateAccount { get; set; }
    [JsonIgnore]
    public virtual Club IdClubNavigation { get; set; }
    
    public virtual Tournament IdTournamentNavigation { get; set; }
    [JsonIgnore]
    public virtual ICollection<PlayerInTournamentClub> PlayerInTournamentClubs { get; set; } = new List<PlayerInTournamentClub>();
}